version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo
    ports:
      - "80:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27016:27017"